version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: llamaflow-n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=5678
      - N8N_PROTOCOL=${N8N_PROTOCOL:-http}
      - N8N_USER_FOLDER=/home/node/.n8n
      - WEBHOOK_URL=${N8N_PROTOCOL:-http}://${N8N_HOST:-localhost}:5678/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE:-America/Sao_Paulo}
    volumes:
      - ./data/n8n:/home/node/.n8n
      - ./src/n8n/workflows:/home/node/.n8n/workflows
      - ./src/n8n/nodes:/home/node/.n8n/nodes
    networks:
      - llamaflow-network

  minio:
    image: minio/minio:latest
    container_name: llamaflow-minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    volumes:
      - ./data/minio:/data
    command: server /data --console-address ":9001"
    networks:
      - llamaflow-network

networks:
  llamaflow-network:
    driver: bridge
