apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: llamaflow-cert
  namespace: llamaflow
spec:
  secretName: llamaflow-tls
  duration: 8760h # 1 year
  renewBefore: 720h # 30 days
  subject:
    organizations:
      - LlamaFlow
  commonName: llamaflow.local
  dnsNames:
    - n8n.local
    - minio.local
    - minio-api.local
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
