apiVersion: v1
kind: Secret
metadata:
  name: n8n-auth
type: Opaque
stringData:
  username: "admin"
  password: "llama123flow"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-config
data:
  N8N_HOST: "localhost"
  N8N_PORT: "5678"
  N8N_PROTOCOL: "http"
  GENERIC_TIMEZONE: "America/Sao_Paulo"
  N8N_BASIC_AUTH_ACTIVE: "true"
  NODE_ENV: "production"
  N8N_USER_FOLDER: "/home/node/.n8n"
  WEBHOOK_URL: "http://localhost:30678/"
  DB_TYPE: "postgresdb"
  DB_POSTGRESDB_HOST: "postgres"
  DB_POSTGRESDB_PORT: "5432"
  DB_POSTGRESDB_DATABASE: "n8n"
  DB_POSTGRESDB_USER: "n8n"
  DB_POSTGRESDB_PASSWORD: "n8npass"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
      initContainers:
      - name: wait-for-postgres
        image: busybox
        command: ['sh', '-c', 'until nc -z postgres 5432; do echo waiting for postgres; sleep 2; done;']
      containers:
      - name: n8n
        image: n8nio/n8n:latest
        command: ["n8n"]
        args: ["start"]
        ports:
        - containerPort: 5678
        envFrom:
        - configMapRef:
            name: n8n-config
        env:
        - name: N8N_BASIC_AUTH_USER
          valueFrom:
            secretKeyRef:
              name: n8n-auth
              key: username
        - name: N8N_BASIC_AUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: n8n-auth
              key: password
        volumeMounts:
        - name: n8n-data
          mountPath: /home/node/.n8n
        - name: workflows
          mountPath: /home/node/.n8n/workflows
        - name: nodes
          mountPath: /home/node/.n8n/nodes
      volumes:
      - name: n8n-data
        hostPath:
          path: /opt/local-path-provisioner/n8n
          type: DirectoryOrCreate
      - name: workflows
        hostPath:
          path: /home/maicos/workspace/maicos/novo_mundo/projects/myflow/LlamaFlow/src/n8n/workflows
          type: DirectoryOrCreate
      - name: nodes
        hostPath:
          path: /home/maicos/workspace/maicos/novo_mundo/projects/myflow/LlamaFlow/src/n8n/nodes
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: n8n
spec:
  type: NodePort
  ports:
  - port: 5678
    targetPort: 5678
    nodePort: 30678
  selector:
    app: n8n
